/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final_380_project;

import cpit380practice.FileChooser;
import cpit380practice.FrameSequencer;
import cpit380practice.Picture;
import cpit380practice.Sound;
import cpit380practice.SoundSample;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JFileChooser;

/**
 *
 * @author almas
 */
public class Move_effects extends javax.swing.JFrame {

    /**
     * Creates new form Mov
     */
    public Move_effects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        req_move = new javax.swing.JButton();
        FramesNum = new javax.swing.JTextField();
        Dropped_ball = new javax.swing.JButton();
        F_num = new javax.swing.JTextField();
        Sunset_mo = new javax.swing.JButton();
        Sun_num = new javax.swing.JTextField();
        Subtrac = new javax.swing.JButton();
        sub = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        edge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        req_move.setText("req_move");
        req_move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                req_moveActionPerformed(evt);
            }
        });

        FramesNum.setBackground(new java.awt.Color(204, 204, 204));

        Dropped_ball.setText("Dropped_ball");
        Dropped_ball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dropped_ballActionPerformed(evt);
            }
        });

        F_num.setBackground(new java.awt.Color(204, 204, 204));

        Sunset_mo.setText("Sunset_move");
        Sunset_mo.setActionCommand("");
        Sunset_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunset_moActionPerformed(evt);
            }
        });

        Sun_num.setBackground(new java.awt.Color(204, 204, 204));

        Subtrac.setText("Subtraction");
        Subtrac.setActionCommand("");
        Subtrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtracActionPerformed(evt);
            }
        });

        sub.setBackground(new java.awt.Color(204, 204, 204));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        jButton2.setText("Edge Detiction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        edge.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Move Effects");

        jButton3.setText("BONUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel2.setText("Please enter the duration for any filter befor click on buttons:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(94, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(req_move, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(FramesNum))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(F_num, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(Dropped_ball, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Sun_num, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edge, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Sunset_mo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Subtrac, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(req_move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Sunset_mo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Dropped_ball, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Subtrac, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FramesNum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F_num, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sun_num, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edge, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void req_moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_req_moveActionPerformed

        
        int Frames_num = Integer.valueOf(FramesNum.getText());
        
        Picture p = null;
        Graphics g = null;
        
        FrameSequencer frameSequencer = new FrameSequencer("req_Move");
        frameSequencer.setShown(true);
        
        for (int i = 0; i < Frames_num; i++) {
            
            
            p = new Picture(Frames_num * 5,Frames_num * 5);
            
            g = p.getGraphics();
            g.setColor(Color.yellow);
            
            g.fillRect(i * 10, i * 10, 100, 100);
            
            frameSequencer.addFrame(p);
        }
        //-4-
        frameSequencer.play(Frames_num);

    }//GEN-LAST:event_req_moveActionPerformed

    private void Dropped_ballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dropped_ballActionPerformed

            int framesPerSec = Integer.valueOf(F_num.getText());
            
            Picture p = null;
            Graphics g = null;
            FrameSequencer frameSequencer = new FrameSequencer("Dropball");

            
            int distance = 300;
            int height = 480;
            
            int start = (height - 50) - distance; //130 stop and down 
           
            for (int i = 0; i < framesPerSec ; i++) {
                p = new Picture(640, height); // shap picture
                g = p.getGraphics();
                
                int y = (int) (Math.sin(30 + (i)) * distance) + start; //schot
                
                if (y > (height - 50 - 10)) {
                    
                    distance = distance / 2;
                    start = (height - 50) - distance;
                     g.setColor(Color.GRAY);
                     g.fillOval(i * 19, y, 60, 50);
                     
                }else{
                y = (int) (Math.sin(30 + (i)) * distance)   + start;
                g.setColor(Color.GRAY);
                g.fillOval(i * 19, y, 50, 50);  
                }

                // add frame to sequencer
                frameSequencer.addFrame(p);
            }
            // play the movie
            frameSequencer.play(framesPerSec);
    }//GEN-LAST:event_Dropped_ballActionPerformed

    private void Sunset_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunset_moActionPerformed
        
        
            int value=Integer.parseInt(Sun_num.getText());
            
                String path = FileChooser.pickAFile();
                Picture beachP = new Picture(path);
                double amountReduction = 1;

                Picture temp = null;
                
                FrameSequencer frameSeq= new FrameSequencer("dir");
                

                // loop creating the frames
                for (int i = 0; i < value * 15; i++) {
                    
                    temp = new Picture(beachP);
                    
                    amountReduction = amountReduction * 0.95;
                    
                    if (amountReduction < value) {
                        
                        temp.makeSunset(amountReduction);
                    } 
                    
                    frameSeq.addFrame(temp);
                }
                // play the movie
                frameSeq.play(value);

    }//GEN-LAST:event_Sunset_moActionPerformed

    private void SubtracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtracActionPerformed
  
        
        String text = sub.getText();
            int time=Integer.parseInt(text);
            
            JFileChooser fc = new JFileChooser("C:\\Users\\almas\\Downloads\\MediaSources");
            fc.showOpenDialog(null);
            String foreground = fc.getSelectedFile().getAbsolutePath();
            Picture foregroundPic = null;

            fc.showOpenDialog(null);
            String oldBackG = fc.getSelectedFile().getAbsolutePath();
            Picture oldBGPic = new Picture(oldBackG);

            fc.showOpenDialog(null);
            String newBackG = fc.getSelectedFile().getAbsolutePath();
            Picture newBGPic = new Picture(newBackG);

            // declare other variables
            FrameSequencer frameSequencer = new FrameSequencer("Movie_Edit");
            int framesPerSec = 30;
            frameSequencer.setShown(true);
            // loop creating the frames
            for (int i = 0; i < framesPerSec * time; i++) {
                foregroundPic = new Picture(foreground);
                foregroundPic.swapBackground(oldBGPic, newBGPic, i);
                frameSequencer.addFrame(foregroundPic);
            }
            // play the movie
            frameSequencer.play(framesPerSec);
        
    }//GEN-LAST:event_SubtracActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


       Picture pic = new Picture("C:\\Users\\almas\\OneDrive\\سطح المكتب\\CPIT 380_LAB\\IN LAB\\lab3\\cpit380practice\\11.png");
        // declare other variables
        Picture target = null;
        FrameSequencer frameSequencer = new FrameSequencer("edgedetection");

        int framesPerSec = Integer.parseInt(edge.getText());

        // loop creating the frames
        for (int i = 0; i < framesPerSec; i++) {
            target = new Picture(pic);
            target.edgeDetection(30 - i);
            frameSequencer.addFrame(target);
        }

        // play the movie
        frameSequencer.play(framesPerSec);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Sound sound_move = new Sound(FileChooser.pickAFile()); 
        SoundSample [] samples = sound_move.getSamples();
        SoundSample sam = null;
        
        int value;
        int framesPerSec = 100;
        Picture p = null;
        Graphics g = null;
        // -1-
        FrameSequencer frameSequencer = new FrameSequencer("BONUS");
        frameSequencer.setShown(true);
        Font font= new Font("Monospaced", Font.ITALIC, 40);   
        
        
        for (int i = 0; i < samples.length; i++) {
            
            p = new Picture(1000,1000); //samples.length
            g = p.getGraphics();
            sam = samples[i];
            value = sam.getValue();
            g.setFont(font);  
            g.setColor(Color.DARK_GRAY);
            g.drawString("Somayah & Almas", value+100 ,  i);
           
            //-3-
            frameSequencer.addFrame(p);
        }
        //-4-
        frameSequencer.play(framesPerSec);
        sound_move.play();
    }//GEN-LAST:event_jButton3ActionPerformed

     Main c = null;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if (c == null) {
            c = new Main();
        }
        c.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Move_effects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Move_effects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Move_effects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Move_effects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Move_effects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dropped_ball;
    private javax.swing.JTextField F_num;
    private javax.swing.JTextField FramesNum;
    private javax.swing.JButton Subtrac;
    private javax.swing.JTextField Sun_num;
    private javax.swing.JButton Sunset_mo;
    private javax.swing.JTextField edge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton req_move;
    private javax.swing.JTextField sub;
    // End of variables declaration//GEN-END:variables
}
